<?php
/** Standard report footer */
require __DIR__ . '/setup.php';
?>
<footer class="rpt-page-footer cn-page-footer">
  <div class="rpt-thanks cn-thanks">Thank you for choosing <?php echo htmlspecialchars($brand['name'] ?? 'TS Transport'); ?></div>
  <?php if ($footerPhoneDisplay !== ''): ?>
  <div class="rpt-contact cn-contact">
    <span>Tel: <?php echo htmlspecialchars($footerPhoneDisplay); ?></span>
  </div>
  <?php endif; ?>
  <div class="rpt-footer-meta">
    <span>Printed: <?php echo htmlspecialchars($reportPrintDate); ?></span>
    <span>·</span>
    <span>Generated by System</span>
    <span class="rpt-page-num"></span>
  </div>
</footer>
