<?php
/**
 * Master report template — presentation variables only.
 * Include before letterhead / info_panel / footer partials.
 *
 * Optional overrides (set in view before include):
 *   $reportTitle, $reportSubtitle, $reportMetaItems, $reportInfoItems,
 *   $reportBranch, $reportPeriod, $reportPreparedBy, $reportShowInfoPanel
 */
if (!isset($brand) || !is_array($brand)) {
    $brand = Helpers::company();
}

$logoArch = '#' . (preg_replace('/[^0-9a-fA-F]/', '', $brand['logo_arch_color'] ?? 'c00') ?: 'c00');
$logoBarBg = '#' . (preg_replace('/[^0-9a-fA-F]/', '', $brand['logo_bar_bg'] ?? '000') ?: '000');
$logoBarColor = '#' . (preg_replace('/[^0-9a-fA-F]/', '', $brand['logo_bar_color'] ?? 'fff') ?: 'fff');
$logoTitleColor = '#' . (preg_replace('/[^0-9a-fA-F]/', '', $brand['logo_title_color'] ?? 'c00') ?: 'c00');
foreach (['logoArch', 'logoBarBg', 'logoBarColor', 'logoTitleColor'] as $__lv) {
    if (strlen($$__lv) === 4) {
        $c = $$__lv[1] . $$__lv[1] . $$__lv[2] . $$__lv[2] . $$__lv[3] . $$__lv[3];
        $$__lv = '#' . $c;
    }
}

$useLogoImage = (($brand['logo_display'] ?? 'builtin') === 'image') && !empty($brand['logo_url']);
$logoInitials = trim($brand['logo_initials'] ?? 'TS') ?: 'TS';
$logoInitials = preg_replace('/[^A-Za-z0-9]/', '', $logoInitials);
$logoInitials = function_exists('mb_substr') ? mb_substr($logoInitials, 0, 6) : substr($logoInitials, 0, 6);
$logoInitials = $logoInitials ?: 'TS';

$reportTitle = trim((string)($reportTitle ?? ($accTitle ?? '')));
$reportSubtitle = trim((string)($reportSubtitle ?? ($brand['tagline'] ?? 'Courier & Parcel Service')));
if ($reportSubtitle === '') {
    $reportSubtitle = 'Courier & Parcel Service';
}

$__user = class_exists('Auth') ? Auth::user() : null;
$reportPreparedBy = trim((string)($reportPreparedBy ?? ($__user['name'] ?? ($__user['username'] ?? ''))));
$reportBranch = trim((string)($reportBranch ?? ($__user['branch_name'] ?? '')));
$reportPrintDate = trim((string)($reportPrintDate ?? date('d/m/Y H:i')));

if (!isset($reportPeriod) || trim((string)$reportPeriod) === '') {
    $reportPeriod = '';
    if (!empty($fromDate) && !empty($toDate)) {
        $reportPeriod = (string)$fromDate . ' — ' . (string)$toDate;
    } elseif (!empty($from) && !empty($to)) {
        $reportPeriod = (string)$from . ' — ' . (string)$to;
    }
}

if (!isset($reportMetaItems) || !is_array($reportMetaItems)) {
    $reportMetaItems = [];
    if ($reportTitle !== '') {
        $reportMetaItems[] = ['label' => 'Report', 'value' => $reportTitle];
    }
    $reportMetaItems[] = ['label' => 'Print Date', 'value' => $reportPrintDate];
    if ($reportPeriod !== '') {
        $reportMetaItems[] = ['label' => 'Period', 'value' => $reportPeriod];
    }
    if ($reportBranch !== '') {
        $reportMetaItems[] = ['label' => 'Branch', 'value' => $reportBranch];
    }
    if ($reportPreparedBy !== '') {
        $reportMetaItems[] = ['label' => 'Generated By', 'value' => $reportPreparedBy];
    }
}

if (!isset($reportInfoItems) || !is_array($reportInfoItems)) {
    $reportInfoItems = [];
    if ($reportTitle !== '') {
        $reportInfoItems[] = ['label' => 'Report Name', 'value' => $reportTitle];
    }
    if ($reportBranch !== '') {
        $reportInfoItems[] = ['label' => 'Branch', 'value' => $reportBranch];
    }
    if ($reportPeriod !== '') {
        $reportInfoItems[] = ['label' => 'Period', 'value' => $reportPeriod];
    }
    if ($reportPreparedBy !== '') {
        $reportInfoItems[] = ['label' => 'Prepared By', 'value' => $reportPreparedBy];
    }
    $reportInfoItems[] = ['label' => 'Printed Date', 'value' => $reportPrintDate];
}

$reportShowInfoPanel = isset($reportShowInfoPanel) ? (bool)$reportShowInfoPanel : (count($reportInfoItems) > 0);

$footerPhoneDisplay = trim((string)($footerPhoneDisplay ?? ''));
if ($footerPhoneDisplay === '') {
    $defaultBranch = Helpers::companyDefaultBranch();
    $footerPhoneDisplay = trim((string)($defaultBranch['phones'] ?? ''));
    if ($footerPhoneDisplay !== '') {
        $footerPhoneDisplay = str_replace('|', ' | ', $footerPhoneDisplay);
    }
}
