<?php

declare(strict_types=1);

/**
 * Busy / Tally-style simple voucher entry.
 *
 * User enters party lines only. When Debit ≠ Credit, the payment-mode account
 * (CASH / BANK / CHEQUE) is appended as the automatic balancing line so the
 * voucher is always complete double-entry before posting.
 *
 * Does not alter Debit/Credit amounts the user entered — only adds the missing side.
 */
class VoucherAutoLedgerService
{
    /** @var list<string> */
    private const AUTO_LEDGER_TYPES = ['PAYMENT', 'RECEIPT', 'JOURNAL', 'CONTRA'];

    public static function supportsAutoLedger(string $voucherType): bool
    {
        return in_array(strtoupper(trim($voucherType)), self::AUTO_LEDGER_TYPES, true);
    }

    public static function normalizePaymentMode(string $paymentMode): string
    {
        return AccountingPaymentModeSettingsRepository::normalizePaymentMode($paymentMode);
    }

    /**
     * @param list<array<string, mixed>> $rawDetails
     * @return list<array<string, mixed>>
     */
    public static function buildCompleteDetails(
        PDO $pdo,
        string $voucherType,
        string $paymentMode,
        array $rawDetails,
        ?string $headerNarration = null
    ): array {
        $lines = self::stripMeta($rawDetails);
        self::validateSimpleLines($lines);

        if (!self::supportsAutoLedger($voucherType)) {
            return $lines;
        }

        $sumDebit = 0.0;
        $sumCredit = 0.0;
        foreach ($lines as $line) {
            $sumDebit += (float) ($line['debit_amount'] ?? 0);
            $sumCredit += (float) ($line['credit_amount'] ?? 0);
        }

        $diff = round($sumDebit - $sumCredit, 2);
        if (abs($diff) < 0.009) {
            return $lines;
        }

        $modeAccountId = AccountingPaymentModeSettingsRepository::getAccountIdForMode($pdo, $paymentMode);
        if ($modeAccountId === null || $modeAccountId <= 0) {
            throw new InvalidArgumentException(
                'Payment mode account is not configured for ' . strtoupper(trim($paymentMode))
                . '. Set it under Accounting → Settings before saving.'
            );
        }

        // Do not auto-post onto an account the user already used on a party line
        // when that would create an ambiguous balancing entry — still allowed if
        // they used cash as party; balancing still uses payment-mode account.
        $narration = trim((string) ($headerNarration ?? ''));
        if ($narration === '') {
            $narration = 'Auto balancing (' . self::normalizePaymentMode($paymentMode) . ')';
        } else {
            $narration = 'Auto: ' . $narration;
        }

        if ($diff > 0) {
            // Excess debit → credit payment-mode account (e.g. Cash Payment)
            $lines[] = [
                'account_id' => $modeAccountId,
                'debit_amount' => 0.0,
                'credit_amount' => abs($diff),
                'narration' => $narration,
                'cost_center_id' => null,
                'is_auto_generated' => true,
            ];
        } else {
            // Excess credit → debit payment-mode account (e.g. Cash Receipt)
            $lines[] = [
                'account_id' => $modeAccountId,
                'debit_amount' => abs($diff),
                'credit_amount' => 0.0,
                'narration' => $narration,
                'cost_center_id' => null,
                'is_auto_generated' => true,
            ];
        }

        return $lines;
    }

    /**
     * @param list<array<string, mixed>> $details
     * @return list<array<string, mixed>>
     */
    public static function markAutoGeneratedLines(
        PDO $pdo,
        string $voucherType,
        string $paymentMode,
        array $details
    ): array {
        foreach ($details as &$line) {
            if (!isset($line['is_auto_generated'])) {
                $line['is_auto_generated'] = false;
            }
        }
        unset($line);

        return $details;
    }

    /**
     * @param list<array<string, mixed>> $rawDetails
     */
    public static function validateSimpleLines(array $rawDetails): void
    {
        $validCount = 0;
        foreach ($rawDetails as $index => $line) {
            if (!is_array($line)) {
                continue;
            }
            $accountId = (int) ($line['account_id'] ?? 0);
            $debit = (float) ($line['debit_amount'] ?? 0);
            $credit = (float) ($line['credit_amount'] ?? 0);

            if ($accountId <= 0 && $debit <= 0 && $credit <= 0) {
                continue;
            }

            if ($accountId <= 0) {
                throw new InvalidArgumentException('Account is required on line ' . ($index + 1) . '.');
            }

            if ($debit < 0 || $credit < 0) {
                throw new InvalidArgumentException('Amounts cannot be negative on line ' . ($index + 1) . '.');
            }

            if (!is_finite($debit) || !is_finite($credit)) {
                throw new InvalidArgumentException('Invalid amount on line ' . ($index + 1) . '.');
            }

            if ($debit <= 0 && $credit <= 0) {
                throw new InvalidArgumentException('Enter a debit or credit amount on line ' . ($index + 1) . '.');
            }

            if ($debit > 0 && $credit > 0) {
                throw new InvalidArgumentException(
                    'Enter either Debit or Credit on line ' . ($index + 1) . ', not both.'
                );
            }

            $validCount++;
        }

        if ($validCount < 1) {
            throw new InvalidArgumentException('At least one voucher line is required.');
        }
    }

    /**
     * @param list<array<string, mixed>> $details
     * @return list<array<string, mixed>>
     */
    private static function stripMeta(array $details): array
    {
        return array_map(static function (array $line): array {
            unset($line['amount']);

            return $line;
        }, $details);
    }

    /**
     * @param list<array<string, mixed>> $details
     * @return list<array<string, mixed>>
     */
    public static function detailsForStorage(array $details): array
    {
        $stored = [];
        foreach ($details as $line) {
            $stored[] = [
                'account_id' => (int) ($line['account_id'] ?? 0),
                'debit_amount' => (float) ($line['debit_amount'] ?? 0),
                'credit_amount' => (float) ($line['credit_amount'] ?? 0),
                'narration' => $line['narration'] ?? null,
                'cost_center_id' => $line['cost_center_id'] ?? null,
            ];
        }

        return $stored;
    }
}
