<?php

declare(strict_types=1);

/**
 * Manual voucher line validation and normalization.
 *
 * Saves only user-entered lines — never creates cash / balancing / counter entries.
 */
class VoucherAutoLedgerService
{
    public static function normalizePaymentMode(string $paymentMode): string
    {
        return AccountingPaymentModeSettingsRepository::normalizePaymentMode($paymentMode);
    }

    /**
     * Passthrough for callers that formerly expected auto-complete behaviour.
     * Returns user lines unchanged (no balancing insert).
     *
     * @param list<array<string, mixed>> $rawDetails
     * @return list<array<string, mixed>>
     */
    public static function buildCompleteDetails(
        PDO $pdo,
        string $voucherType,
        string $paymentMode,
        array $rawDetails,
        ?string $headerNarration = null
    ): array {
        unset($pdo, $voucherType, $paymentMode, $headerNarration);
        $lines = self::stripMeta($rawDetails);
        self::validateSimpleLines($lines);

        return $lines;
    }

    /**
     * @deprecated Auto-ledger is permanently disabled (manual entry only).
     */
    public static function supportsAutoLedger(string $voucherType): bool
    {
        unset($voucherType);

        return false;
    }

    /**
     * @param list<array<string, mixed>> $details
     * @return list<array<string, mixed>>
     */
    public static function markAutoGeneratedLines(
        PDO $pdo,
        string $voucherType,
        string $paymentMode,
        array $details
    ): array {
        unset($pdo, $voucherType, $paymentMode);
        foreach ($details as &$line) {
            $line['is_auto_generated'] = false;
        }
        unset($line);

        return $details;
    }

    /**
     * @param list<array<string, mixed>> $rawDetails
     */
    public static function validateSimpleLines(array $rawDetails): void
    {
        $validCount = 0;
        foreach ($rawDetails as $index => $line) {
            if (!is_array($line)) {
                continue;
            }
            $accountId = (int) ($line['account_id'] ?? 0);
            $debit = (float) ($line['debit_amount'] ?? 0);
            $credit = (float) ($line['credit_amount'] ?? 0);

            if ($accountId <= 0 && $debit <= 0 && $credit <= 0) {
                continue;
            }

            if ($accountId <= 0) {
                throw new InvalidArgumentException('Account is required on line ' . ($index + 1) . '.');
            }

            if ($debit < 0 || $credit < 0) {
                throw new InvalidArgumentException('Amounts cannot be negative on line ' . ($index + 1) . '.');
            }

            if (!is_finite($debit) || !is_finite($credit)) {
                throw new InvalidArgumentException('Invalid amount on line ' . ($index + 1) . '.');
            }

            if ($debit <= 0 && $credit <= 0) {
                throw new InvalidArgumentException('Enter a debit or credit amount on line ' . ($index + 1) . '.');
            }

            if ($debit > 0 && $credit > 0) {
                throw new InvalidArgumentException(
                    'Enter either Debit or Credit on line ' . ($index + 1) . ', not both.'
                );
            }

            $validCount++;
        }

        if ($validCount < 1) {
            throw new InvalidArgumentException('At least one voucher line is required.');
        }
    }

    /**
     * @param list<array<string, mixed>> $details
     * @return list<array<string, mixed>>
     */
    private static function stripMeta(array $details): array
    {
        return array_map(static function (array $line): array {
            unset($line['amount'], $line['is_auto_generated']);

            return $line;
        }, $details);
    }

    /**
     * @param list<array<string, mixed>> $details
     * @return list<array<string, mixed>>
     */
    public static function detailsForStorage(array $details): array
    {
        $stored = [];
        foreach ($details as $line) {
            $stored[] = [
                'account_id' => (int) ($line['account_id'] ?? 0),
                'debit_amount' => (float) ($line['debit_amount'] ?? 0),
                'credit_amount' => (float) ($line['credit_amount'] ?? 0),
                'narration' => $line['narration'] ?? null,
                'cost_center_id' => $line['cost_center_id'] ?? null,
            ];
        }

        return $stored;
    }
}
