-- Transfer Voucher module schema (additive only)
CREATE TABLE IF NOT EXISTS transfer_vouchers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  voucher_no VARCHAR(50) NOT NULL,
  sequence_no INT UNSIGNED NOT NULL,
  fiscal_year VARCHAR(10) NOT NULL,
  voucher_date DATE NOT NULL,
  from_account_id INT UNSIGNED NOT NULL,
  to_account_id INT UNSIGNED NOT NULL,
  amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  reference_number VARCHAR(100) NULL DEFAULT NULL,
  narration TEXT NULL,
  status ENUM('DRAFT','POSTED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
  cashbook_transfer_id INT UNSIGNED NULL DEFAULT NULL,
  created_by INT UNSIGNED NULL DEFAULT NULL,
  posted_by INT UNSIGNED NULL DEFAULT NULL,
  cancelled_by INT UNSIGNED NULL DEFAULT NULL,
  posted_at DATETIME NULL DEFAULT NULL,
  cancelled_at DATETIME NULL DEFAULT NULL,
  cancel_reason TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_transfer_voucher_no (voucher_no),
  UNIQUE KEY uq_transfer_voucher_seq (fiscal_year, sequence_no),
  KEY idx_transfer_voucher_status (status),
  KEY idx_transfer_voucher_date (voucher_date),
  KEY idx_transfer_voucher_created_by (created_by),
  KEY idx_transfer_voucher_posted_at (posted_at),
  KEY idx_transfer_voucher_cashbook_transfer (cashbook_transfer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;